### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Gcaufy** [univerone/words-per-day#1]
功能很棒，代码整洁。超过预期~

以下提出一些 Code Review 建议:

> src/index.ts18

如果是有限类型，为何不是 enum 或者 type?

> src/index.ts:36

为何使用 Partial, 这里是不是可以用选填属性呢？

> src/index.ts:68

为何声明 any?

> src/index.ts:90

参数过多

> src/index.ts:98

去 console.log

> src/index.ts:112

只支持配置单个房间吗？

> src/utils.ts:62

多余 Promise

其它可以做得更好的地方：

1. 代码注释规范统一，建议使用 JSDoc 注释规范。
2. 去除无用代码，如 console.log， 以及纠正部分命名，如 Dingdong。
3. 文件名不使用中文。源码无关图片不放入 git 管理。
4. 关注代码异常处理，对于 await, promise 的异常捕捉。
5. 逻辑进一步抽象，如数据拉取部分，未来支持数据源可配等更灵活的能力。
6. 图片处理依赖文件存储，多次读写。是否可以考虑优化为使用二进制或者 stream。
7. 测试用例补齐。
8. CI 集成， npm 发布。

**Comment by huan** [comment]
Congratulations to @Gcaufy and @univerone !

We are so efficient that get this great progress right after we kicked off our SoC, thank you for your effect for making the Wechaty better, and I'm looking forward to seeing this project becomes Alpha and using it by myself. Cheers!

**Comment by Gcaufy** [comment]
Use Weekly Report instead: https://github.com/wechaty/summer-of-code/issues/10#issuecomment-667651942
